#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys
from .ttypes import *
TSENTRY_SERVICE_V1 = 1
TSENTRY_SERVICE_V2 = 2
TSENTRY_STATUS_OK = 0
TSENTRY_STATUS_ALREADY_EXISTS = 1
TSENTRY_STATUS_NO_SUCH_OBJECT = 2
TSENTRY_STATUS_RUNTIME_ERROR = 3
TSENTRY_STATUS_INVALID_INPUT = 4
TSENTRY_STATUS_ACCESS_DENIED = 5
TSENTRY_STATUS_THRIFT_VERSION_MISMATCH = 6
